var num1=10;
var num2=3;
sum=num1+num2;
sub=num1-num2;
mul= num1*num2;
div=num1/num2;
mod=num1%num2;
power=num1**num2;
// console.log(sum=num1+num2);
// console.log(sub=num1-num2);
// console.log(mul= num1*num2);
// console.log(div=num1/num2);
// console.log(mod=num1%num2);
// console.log(power=num1**num2);
console.log(`sum=${sum}`);
console.log(`sub=${sub}`);
console.log(`mul=${mul}`);
console.log(`division is ${div}`);
console.log(`mod=${mod}`);
console.log(`power=${power}`);

console.log(`final result of sum, sub , mul, div, mode and power are ${sum}, ${sub},${mul}, ${div}, ${mod} and ${power} consequently `);